[package]
name = "zklend_flash_loan"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.1"
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
snforge_std = "0.38.3"
assert_macros = "2.11.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[[tool.snforge.fork]]
name = "MAINNET_FORK_609051"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/"
block_id.number = "609051"
